### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sztomi** [pfultz2/cmake-get#2]
I have the following cmake script:

```cmake
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)

include(CMakeGet)

cmake_get(pfultz2/cget-recipes
          PREFIX ${CMAKE_CURRENT_BINARY_DIR}/deps)
cmake_get_from(${CMAKE_SOURCE_DIR}/requirements.txt
          PREFIX ${CMAKE_CURRENT_BINARY_DIR}/deps)
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_BINARY_DIR}/deps)
```

My requirements.txt has the following contents:

```
boost
sfml
nlohmann/json
fmtlib/fmt
```

When I configure the project, I get the foloowing error (after downloading a number of packages):

```
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    /boost.cmake


-- Configuring incomplete, errors occurred!
See also "/private/var/folders/d0/czkmg12j3036n3_skqccd62w0000gn/T/cget-23-35-10-DvU0L-1/build/CMakeFiles/CMakeOutput.log".
CMake Error at cmake/CMakeGet.cmake:130 (message):
  Process failed:
  COMMAND;/usr/local/Cellar/cmake/3.9.2/bin/cmake;-DCMAKE_PREFIX_PATH=/Users/tamas/work/JacobInTheDark/build/deps;-DCMAKE_INSTALL_PREFIX=/Users/tamas/work/JacobInTheDark/build/deps;-DCGET_CMAKE_ORIGINAL_SOURCE_FILE=/var/folders/d0/czkmg12j3036n3_skqccd62w0000gn/T/cget-23-35-10-DvU0L-1/download/boost_1_64_0/__cget_original_cmake_file__.cmake;-DBOOST_WITHOUT_CONTEXT=1;-DBOOST_WITHOUT_COROUTINE=1;-DBOOST_WITHOUT_COROUTINE2=1;-DBOOST_WITHOUT_PYTHON=1;/var/folders/d0/czkmg12j3036n3_skqccd62w0000gn/T/cget-23-35-10-DvU0L-1/download/boost_1_64_0;WORKING_DIRECTORY;/var/folders/d0/czkmg12j3036n3_skqccd62w0000gn/T/cget-23-35-10-DvU0L-1/build
Call Stack (most recent call first):
  cmake/CMakeGet.cmake:161 (cget_exec)
  cmake/CMakeGet.cmake:354 (cget_install_dir)
  cmake/CMakeGet.cmake:405 (cmake_get)
  cmake/CMakeGet.cmake:336 (cmake_get_from)
  cmake/CMakeGet.cmake:405 (cmake_get)
  CMakeLists.txt:11 (cmake_get_from)
```

I suspect that this is because there is a variable before `/boost.cmake` that is expanded to nothing. But I don't know where this cmake script is located to further debug.

I've pasted to full output here: https://pastebin.com/DM8C0Mb1

**Comment by pfultz2** [comment]
> But I don't know where this cmake script is located to further debug.

It downloads the cmake file from cget, [here](https://github.com/pfultz2/cget/blob/master/cget/cmake/boost.cmake), which looks like it failed to download. Let me look into improving this diagnostics.

**Comment by vallahaye** [comment]
Any update on this issue ? I'm having the exact same problem.

**Comment by pfultz2** [comment]
I see the issue. The problem is this doesn't support the `CGET_CMAKE_DIR` variable, which is used in the boost recipe [here](https://github.com/pfultz2/cget-recipes/blob/master/recipes/boost/build.cmake#L9). I think the boost.cmake has been updated, so the boost recipe no longer needs to use `CGET_CMAKE_DIR`. Let me fix the boost recipe.

In the future, I would like to move cget cmake files into a separate project that can be installed instead of just grabbing the file on demand.

**Comment by vallahaye** [comment]
I see. Moving cget cmake files into a separate project seems a bit too much to me. Maybe should you just add a target to install them on demand into the global CMake modules directory ? Your fix on the boost recipe works very well, I guess this issue can be closed.
